// Reproducible build of Eucalculia_v8.html.
//   node Eucalculia_v8_handoff/build/build_v8.mjs            (run from the "Eucalculia 6.0" folder)
// 1. Reads Eucalculia_experimental.html (never written).
// 2. Applies build/source_patches.json + build/manual_patches.json as exact, counted replacements.
// 3. Generates the embedded SPA-VER content engine from Eucalculia_SPA_VER_01_prototype.html (never written).
// 4. Appends the v8 modules listed in v8_src/manifest.json.
// 5. Writes Eucalculia_v8.html and checks that the four protected source files are unchanged.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = process.cwd();
const HANDOFF = path.join(ROOT, 'Eucalculia_v8_handoff');
const PROTECTED = ['Eucalculia.html', 'Eucalculia_suave.html', 'Eucalculia_experimental.html', 'Eucalculia_SPA_VER_01_prototype.html'];
const sha = (f) => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, f))).digest('hex');
const before = Object.fromEntries(PROTECTED.map((f) => [f, sha(f)]));

let html = fs.readFileSync(path.join(ROOT, 'Eucalculia_experimental.html'), 'utf8');
if (!html.includes('\r\n')) throw new Error('expected CRLF source');

// ---- 2. source patches -------------------------------------------------------------------
const patchFiles = ['source_patches.json', 'manual_patches.json'].map((f) => path.join(HANDOFF, 'build', f)).filter((f) => fs.existsSync(f));
const seen = new Set();
let applied = 0;
for (const file of patchFiles) {
  for (const p of JSON.parse(fs.readFileSync(file, 'utf8'))) {
    const key = p.find + '\u0000' + p.replace;
    if (seen.has(key)) continue; seen.add(key);
    const find = p.find.replace(/\r?\n/g, '\r\n'), replace = p.replace.replace(/\r?\n/g, '\r\n');
    const count = html.split(find).length - 1;
    const expected = p.count ?? 1;
    if (count !== expected) throw new Error(`patch ${p.id || p.line}: expected ${expected} occurrence(s), found ${count}`);
    html = html.split(find).join(replace);
    applied++;
  }
}

// ---- 3. SPA-VER engine extraction ---------------------------------------------------------
const proto = fs.readFileSync(path.join(ROOT, 'Eucalculia_SPA_VER_01_prototype.html'), 'utf8');
const startMarker = 'const APP_VERSION="SPA-VER-01 v22";';
const endMarker = '/* ═══ TELEMETRY + PERSISTENCE ═══';
const s = proto.indexOf(startMarker), e = proto.indexOf(endMarker);
if (s < 0 || e < 0 || e <= s) throw new Error('SPA-VER engine markers not found');
let engine = proto.slice(s, e);
if (/document\.|localStorage|\bState\./.test(engine)) throw new Error('SPA-VER engine slice is not DOM-free');
// The prototype seeds from ?seed= or Date.now(); inside Eucalculia the seed is always injected.
engine = engine.replace(/let SEED=\(\(\)=>\{[^\n]*\n/, 'let SEED=0x5EED5EED>>>0;\n');
if (!/let SEED=0x5EED5EED>>>0;/.test(engine)) throw new Error('SEED initialiser not replaced');
const engineHeader = '/* Generated by build_v8.mjs from Eucalculia_SPA_VER_01_prototype.html (v22) — content engine only, DOM-free. */\n';
fs.mkdirSync(path.join(HANDOFF, 'v8_src', 'generated'), { recursive: true });
fs.writeFileSync(path.join(HANDOFF, 'v8_src', 'generated', 'spaver_engine.js'), engineHeader + engine);

// ---- 4. v8 modules -----------------------------------------------------------------------
const manifest = JSON.parse(fs.readFileSync(path.join(HANDOFF, 'v8_src', 'manifest.json'), 'utf8'));
const blocks = [];
for (const m of manifest.modules) {
  let body = fs.readFileSync(path.join(HANDOFF, 'v8_src', m.file), 'utf8');
  if (m.inject) for (const [token, file] of Object.entries(m.inject)) {
    const inj = fs.readFileSync(path.join(HANDOFF, 'v8_src', file), 'utf8');
    if (!body.includes(token)) throw new Error(`token ${token} missing in ${m.file}`);
    body = body.split(token).join(inj);
  }
  if (/<\/script/i.test(body) && m.kind === 'script') throw new Error(`${m.file} contains </script>`);
  const id = m.id ? ` id="${m.id}"` : '';
  if (m.kind === 'style') blocks.push(`<style${id}>\n${body}\n</style>`);
  else if (m.kind === 'script') blocks.push(`<script${id}>\n${body}\n</script>`);
  else if (m.kind === 'json') blocks.push(`<script type="application/json"${id}>\n${body}\n</script>`);
  else if (m.kind === 'html') blocks.push(body);
  else throw new Error('unknown module kind ' + m.kind);
}
const trailer = blocks.join('\n').replace(/\r?\n/g, '\r\n');
html = html.replace(/(\r\n)*$/, '') + '\r\n' + trailer + '\r\n';

// ---- 5. write + protect -------------------------------------------------------------------
fs.writeFileSync(path.join(ROOT, 'Eucalculia_v8.html'), html);
const after = Object.fromEntries(PROTECTED.map((f) => [f, sha(f)]));
for (const f of PROTECTED) if (before[f] !== after[f]) throw new Error('PROTECTED FILE CHANGED: ' + f);
console.log(`patches applied: ${applied}; modules: ${manifest.modules.length}; size: ${(html.length / 1e6).toFixed(2)} MB; protected files unchanged`);
